-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\hdlcoder_dwt\alpha4_level_dwt_pkg.vhd
-- Created: 2023-05-02 15:37:17
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE alpha4_level_dwt_pkg IS
  TYPE vector_of_std_logic_vector16 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(15 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_signed51 IS ARRAY (NATURAL RANGE <>) OF signed(50 DOWNTO 0);
  TYPE vector_of_signed70 IS ARRAY (NATURAL RANGE <>) OF signed(69 DOWNTO 0);
  TYPE vector_of_signed89 IS ARRAY (NATURAL RANGE <>) OF signed(88 DOWNTO 0);
  TYPE vector_of_signed108 IS ARRAY (NATURAL RANGE <>) OF signed(107 DOWNTO 0);
  TYPE vector_of_signed127 IS ARRAY (NATURAL RANGE <>) OF signed(126 DOWNTO 0);
END alpha4_level_dwt_pkg;

