-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\full_system_nios_id2\full_system_pkg.vhd
-- Created: 2023-05-25 08:56:44
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE full_system_pkg IS
  TYPE vector_of_std_logic_vector16 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(15 DOWNTO 0);
  TYPE vector_of_signed35 IS ARRAY (NATURAL RANGE <>) OF signed(34 DOWNTO 0);
  TYPE vector_of_signed16 IS ARRAY (NATURAL RANGE <>) OF signed(15 DOWNTO 0);
  TYPE vector_of_signed54 IS ARRAY (NATURAL RANGE <>) OF signed(53 DOWNTO 0);
END full_system_pkg;

