-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\full_system_nios_id7\alpha1_level_dwt2.vhd
-- Created: 2023-05-23 17:24:43
-- 
-- Generated by MATLAB 9.11 and HDL Coder 3.19
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: alpha1_level_dwt2
-- Source Path: full_system_nios_id7/full_system/1_level_dwt2
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.full_system_pkg.ALL;

ENTITY alpha1_level_dwt2 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_8_0                         :   IN    std_logic;
        enb_1_4_0                         :   IN    std_logic;
        enb_1_8_1                         :   IN    std_logic;
        s_in                              :   IN    std_logic_vector(53 DOWNTO 0);  -- sfix54_En4
        enable                            :   IN    std_logic;
        D                                 :   OUT   std_logic_vector(72 DOWNTO 0)  -- sfix73_En4
        );
END alpha1_level_dwt2;


ARCHITECTURE rtl OF alpha1_level_dwt2 IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT Discrete_FIR_Filter_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_4_0                       :   IN    std_logic;
          Discrete_FIR_Filter_in          :   IN    std_logic_vector(53 DOWNTO 0);  -- sfix54_En4
          Discrete_FIR_Filter_coeff       :   IN    vector_of_std_logic_vector16(0 TO 7);  -- int16 [8]
          Discrete_FIR_Filter_out         :   OUT   std_logic_vector(72 DOWNTO 0)  -- sfix73_En4
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Discrete_FIR_Filter_block
    USE ENTITY work.Discrete_FIR_Filter_block(rtl);

  -- Signals
  SIGNAL RT2_bypass_reg                   : std_logic;  -- ufix1
  SIGNAL RT2_out1                         : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant_out1                    : signed(72 DOWNTO 0);  -- sfix73_En4
  SIGNAL db4_wavelet_out1                 : vector_of_signed16(0 TO 7);  -- int16 [8]
  SIGNAL db4_wavelet_out1_1               : vector_of_std_logic_vector16(0 TO 7);  -- ufix16 [8]
  SIGNAL Discrete_FIR_Filter_out1         : std_logic_vector(72 DOWNTO 0);  -- ufix73
  SIGNAL Discrete_FIR_Filter_out1_signed  : signed(72 DOWNTO 0);  -- sfix73_En4
  SIGNAL Downsample_out1                  : signed(72 DOWNTO 0);  -- sfix73_En4
  SIGNAL Switch_out1                      : signed(72 DOWNTO 0);  -- sfix73_En4

BEGIN
  u_Discrete_FIR_Filter : Discrete_FIR_Filter_block
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_4_0 => enb_1_4_0,
              Discrete_FIR_Filter_in => s_in,  -- sfix54_En4
              Discrete_FIR_Filter_coeff => db4_wavelet_out1_1,  -- int16 [8]
              Discrete_FIR_Filter_out => Discrete_FIR_Filter_out1  -- sfix73_En4
              );

  RT2_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      RT2_bypass_reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_1 = '1' THEN
        RT2_bypass_reg <= enable;
      END IF;
    END IF;
  END PROCESS RT2_bypass_process;

  
  RT2_out1 <= enable WHEN enb_1_8_1 = '1' ELSE
      RT2_bypass_reg;

  
  switch_compare_1 <= '1' WHEN RT2_out1 > '0' ELSE
      '0';

  Constant_out1 <= to_signed(0, 73);

  db4_wavelet_out1(0) <= to_signed(16#0000#, 16);
  db4_wavelet_out1(1) <= to_signed(16#0001#, 16);
  db4_wavelet_out1(2) <= to_signed(-16#0001#, 16);
  db4_wavelet_out1(3) <= to_signed(16#0000#, 16);
  db4_wavelet_out1(4) <= to_signed(16#0000#, 16);
  db4_wavelet_out1(5) <= to_signed(16#0000#, 16);
  db4_wavelet_out1(6) <= to_signed(16#0000#, 16);
  db4_wavelet_out1(7) <= to_signed(16#0000#, 16);

  outputgen: FOR k IN 0 TO 7 GENERATE
    db4_wavelet_out1_1(k) <= std_logic_vector(db4_wavelet_out1(k));
  END GENERATE;

  Discrete_FIR_Filter_out1_signed <= signed(Discrete_FIR_Filter_out1);

  -- Downsample output register
  Downsample_output_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Downsample_out1 <= to_signed(0, 73);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb_1_8_0 = '1' THEN
        Downsample_out1 <= Discrete_FIR_Filter_out1_signed;
      END IF;
    END IF;
  END PROCESS Downsample_output_process;


  
  Switch_out1 <= Constant_out1 WHEN switch_compare_1 = '0' ELSE
      Downsample_out1;

  D <= std_logic_vector(Switch_out1);

END rtl;

